### ISSUE TITLE
Angular Beta 16 breaks things

### ISSUE THREAD

**Issue by shaneseaton** [ntrp/meteor-ionic-angular2-starter#1]
You list a dependency to "angular2": "^2.0.0-beta.15", now that beta 16 is out, npm will use that as you have the '^' in front of the version. Unfortunately this break things due to the following bug/issue in beta 16.

https://github.com/angular/angular/issues/8237

easy temporary fix for anyone using this, just force the version to 15. "angular2": "2.0.0-beta.15"

Thanks heaps for the starter though. Its pretty difficult to get going with this stuff, so many moving parts. This definitely helps.

**Comment by ntrp** [comment]
Fixed with latest push. The package versions has been set to fixed.
