### ISSUE TITLE
migrate to ionic 2.0.0-beta.6

### ISSUE THREAD

**Issue by vohtaski** [ntrp/meteor-ionic-angular2-starter#2]
@ntrp have you tried to migrate to the latest ionic beta?

**Comment by ntrp** [comment]
Didn't try it yet but if you want to use beta.6 you can get a glimpse at the required operations here:

https://github.com/driftyco/ionic/blob/2.0/ionic/decorators/app.ts

**Comment by vohtaski** [comment]
thanks! have it working with beta.6 now :)
